language: node_js

node_js: ["stable", "13", "12", "10", "8"]
os: linux

if: tag IS blank

cache: npm

script:
  - npm run build

jobs:
  include:
    - stage: test
      name: audit ğŸ•´ï¸
      node_js: "stable"
      script: npm audit
    - stage: deploy ğŸš€
      name: publish github pages ğŸ“œ
      script: npm run docs
      deploy:
        edge: true # opt in to dpl v2
        provider: pages
        token: $GITHUB_TOKEN
        local_dir: out/docs
        cleanup: false
        verbose: true
        on:
          branch: master
    # - stage: deploy ğŸš€
    #   name: publish npm ğŸ“¦
    #   install: npm ci
    #   script: skip
    #   deploy:
    #     edge: true # opt in to dpl v2
    #     provider: npm
    #     api_token: $NPM_AUTH_TOKEN
    #     cleanup: false
    #     on:
    #       branch: master
    # - stage: tag ğŸ·ï¸
    #   name: publish git release
    #   before_deploy:
    #     - npm pack
    #     - npm version
    #     - git tag
    #     # - git push --tags
    #   deploy:
    #     provider: releases
    #     token: $GITHUB_TOKEN
    #     file: "build-object-better-*.tgz"
    #     file_glob: true
    #     cleanup: false
    #     on:
    #       branch: master
